name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: sqlite, pdo_sqlite
          tools: composer:v2

      - name: Install SVN
        run: sudo apt-get update && sudo apt-get install -y subversion wget

      - name: Install WP-CLI
        run: |
          wget -O /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar; \
          chmod +x /usr/local/bin/wp

      - name: Install dependencies
        run: composer install

      - name: Install WP Tests
        run: bash bin/install-wp-tests.sh

      - name: PHPUnit Tests
        run: ./vendor/bin/phpunit --testdox
